## first step

In [1]:
import numpy as np
import chainer

In [2]:
x_data = np.asarray([2], dtype=np.float32)
y_data = np.asarray([3], dtype=np.float32)

In [3]:
x = chainer.Variable(x_data)
y = chainer.Variable(y_data)

In [5]:
z = x**2 + 10*y - 2
print(z.data)

[ 32.]


In [6]:
z.backward()
print(x.grad)
print(y.grad)

[ 4.]
[ 10.]


## Functions

In [13]:
x.zerograd() # 勾配の初期化
s = chainer.functions.sigmoid(x)
print(s.data)

[ 0.88079709]


In [14]:
s.backward()
print(x.grad)
print(((1-s)*s).data)

[ 0.10499357]
[ 0.10499357]


## Links

In [36]:
fc = chainer.links.Linear(2, 3) #入力2, 出力3の全結合NN層
for name, param in fc.namedparams():
    print(name, param.data.shape) #パラメータ名とサイズ
    print(param.data) #パラメータの値

/W (3, 2)
[[ 0.53433412  0.03996841]
 [-0.12559491 -0.36657995]
 [-1.27918077  0.34596011]]
/b (3,)
[ 0.  0.  0.]


In [38]:
conv = chainer.links.Convolution2D(3, 2, (5,5)) #入力特徴マップ3, 出力特徴マップ2, カーネルサイズ5x5
for name, param in conv.namedparams():
    print(name, param.data.shape) #パラメータ名とサイズ
    print(param.data) #パラメータの値

/W (2, 3, 5, 5)
[[[[ 0.15858957 -0.0748275   0.00352767 -0.10600162 -0.09979915]
   [ 0.12817955  0.03008411  0.01674165  0.08545738  0.10239564]
   [ 0.00252704  0.10119335  0.00759445 -0.14500213 -0.10562113]
   [-0.13388959  0.00271357  0.05773284 -0.13858567 -0.15422632]
   [ 0.01531546 -0.06062151 -0.00527028 -0.11917926 -0.03412564]]

  [[-0.06656039 -0.08426102 -0.00977844 -0.14890613  0.11918887]
   [-0.03666651  0.1831675  -0.10069701  0.0282936   0.07972289]
   [ 0.00762428 -0.02291361  0.03947306  0.03635543  0.15817608]
   [-0.18774261 -0.21085855 -0.17480291  0.02014508  0.00048823]
   [ 0.04985614 -0.03906743  0.08195363  0.149875   -0.06230555]]

  [[-0.15829866 -0.14665368  0.11720715 -0.17458618  0.19159159]
   [-0.01358328 -0.13076594 -0.03243548  0.15710692 -0.01656256]
   [ 0.06290089 -0.0892431   0.08935644 -0.06508955 -0.02945987]
   [ 0.11280536 -0.28148022 -0.04075379  0.02254223  0.0404037 ]
   [-0.10478283  0.06052563  0.24409562  0.00994271  0.10362723]]]


 

In [39]:
# Linkへ投げる入力変数はデータのミニバッチ
d_data = np.asarray([[1,2],                   #1番目のデータ
                    [3,4]], dtype=np.float32) #2番目のデータ
d = chainer.Variable(d_data)
ret = fc(d)
print(ret.data)

[[ 0.61427093 -0.85875481 -0.58726054]
 [ 1.76287591 -1.8431046  -2.45370197]]


In [44]:
# Linkへ投げる入力変数はデータのミニバッチ
d_data = np.asarray([
                    [[[1,2,0,1,2,0], # 1チャンネル目
                      [3,4,0,3,4,0],
                      [5,6,0,5,6,0],
                      [7,8,0,7,8,0],
                      [9,1,0,9,1,0],
                      [2,3,0,2,3,0]],
                     [[1,2,0,1,2,0], # 2チャンネル目
                      [3,4,0,3,4,0],
                      [5,6,0,5,6,0],
                      [7,8,0,7,8,0],
                      [9,1,0,9,1,0],
                      [2,3,0,2,3,0]],
                     [[1,2,0,1,2,0], # 3チャンネル目
                      [3,4,0,3,4,0],
                      [5,6,0,5,6,0],
                      [7,8,0,7,8,0],
                      [9,1,0,9,1,0],
                      [2,3,0,2,3,0]]],
                    # 次のデータが続く...
                    ], dtype=np.float32) #2番目のデータ
d = chainer.Variable(d_data)
ret = conv(d)
print(ret.data)

[[[[-6.05686092 -0.41110778]
   [-2.68121386 -1.07041752]]

  [[ 0.08105962 -0.2516928 ]
   [-4.33526564  0.94333905]]]]
